#!/usr/bin/python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import sys
from lib.activity import activity

def usage():
    usage = """USAGE:
    jgpcro activity_start   # Log start of activity
    """
    print(usage)
    exit();

def main():
    if len(sys.argv) < 2:
        usage()
    elif sys.argv[1] == "activity_start":
        activity("start")
    elif sys.argv[1] == "activity_stop":
        activity("stop")
    else:
        usage()

main()

